In [12]:
import numpy as np
from numpy.linalg import inv

N = 3

def flip_mat(mat, r, c):
    mat[r, c] = 1 - mat[r, c]
    if r >= 1:
        mat[r-1, c] = 1 - mat[r-1, c]
    if c >= 1:
        mat[r, c-1] = 1 - mat[r, c-1]
    if r + 1 < N:
        mat[r+1, c] = 1 - mat[r+1, c]
    if c + 1 < N:
        mat[r, c+1] = 1 - mat[r, c+1]

data = [np.mat(np.zeros((N, N))) for _ in range(N * N)]
for idx in range(N * N):
    r = idx // N
    c = idx % N
    flip_mat(data[idx], r, c)

A = np.mat(np.zeros((N * N, N * N)))
for idx in range(N * N):
    for r in range(N):
        for c in range(N):
            A[r * N + c, idx] = data[idx][r,c]

print(A)

B = inv(A)
print(B)

[[ 1.  1.  0.  1.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  1.  0.  0.  0.  0.]
 [ 0.  1.  1.  0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0.  1.  1.  0.  1.  0.  0.]
 [ 0.  1.  0.  1.  1.  1.  0.  1.  0.]
 [ 0.  0.  1.  0.  1.  1.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.  0.  1.  1.  0.]
 [ 0.  0.  0.  0.  1.  0.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.  1.  1.]]
[[-0.14285714  0.57142857 -0.14285714  0.57142857 -0.28571429 -0.42857143
  -0.14285714 -0.42857143  0.85714286]
 [ 0.57142857 -0.28571429  0.57142857 -0.28571429  0.14285714 -0.28571429
  -0.42857143  0.71428571 -0.42857143]
 [-0.14285714  0.57142857 -0.14285714 -0.42857143 -0.28571429  0.57142857
   0.85714286 -0.42857143 -0.14285714]
 [ 0.57142857 -0.28571429 -0.42857143 -0.28571429  0.14285714  0.71428571
   0.57142857 -0.28571429 -0.42857143]
 [-0.28571429  0.14285714 -0.28571429  0.14285714  0.42857143  0.14285714
  -0.28571429  0.14285714 -0.28571429]
 [-0.42857143 -0.28571429  0.57142857  0.71428571  0.14285714 -0.28571429
  -0.4285

In [13]:
import numpy as np
from numpy.linalg import inv

N = 5

def flip_mat(mat, r, c):
    mat[r, c] = 1 - mat[r, c]
    if r >= 1:
        mat[r-1, c] = 1 - mat[r-1, c]
    if c >= 1:
        mat[r, c-1] = 1 - mat[r, c-1]
    if r + 1 < N:
        mat[r+1, c] = 1 - mat[r+1, c]
    if c + 1 < N:
        mat[r, c+1] = 1 - mat[r, c+1]

data = [np.mat(np.zeros((N, N))) for _ in range(N * N)]
for idx in range(N * N):
    r = idx // N
    c = idx % N
    flip_mat(data[idx], r, c)

A = np.mat(np.zeros((N * N, N * N)))
for idx in range(N * N):
    for r in range(N):
        for c in range(N):
            A[r * N + c, idx] = data[idx][r,c]

print(A)

B = inv(A)
print(B)

[[ 1.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  1.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  1.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  1.  1.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  1.  1.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  1.  1.  1.  0.  0.  0.  1.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  1.  1.  0.  0.  0.  